//String baseUrl = "https://www.dietmaker.com/api/";
String baseUrl = "https://admin.dietmaker.com/api/";

//User
String login = "client/login";
String editProfile = "client/profile";
String editDietaryPreferences = "client/dietary-preferences/";
String updatePassword = "client/change-password";
String logout = "client/logout";
String uploadPhoto = "client/photo";
String forgotPassword = "client/reset-password";
String deactivateAccountUrl = "client/deactive";
String nutrientsVariable = "get-nutrition-target-variables";

// Meal Plans
String mealPlanById = "diet/meal-plans/";
String allMealPlan = "diet/meal-plans";
String createMealPlan = "diet/meal-plans";
String editMealPlan = "diet/meal-plans/";

//Foods
String searchFood = "food/foods/search";
String getFoodDetail = "food/foods/";

//Meal Food Items
String getFoodItemDetails = "diet/meal-foods/";
String getRecipeItemDetails = "diet/meal-recipes/";

//Branded Food
String searchBrandedFood = "branded-food/search";
String getBrandedFoodDetail = "branded-food/";
String getBrandedFoodDetailByUpc = "branded-food/search-by-gtin?gtin_upc=";

//Meal food
String addMealFood = "diet/meal-foods";
String addMealBrandedFood = "diet/meal-branded-foods";

//delete foods
String deleteMealBrandedFood = "diet/meal-branded-foods/";
String deleteMealFood = "diet/meal-foods/";
String deleteMealRecipe = "diet/meal-recipes/";
String deleteMyFood = "client/foods/";
String deleteMyFoodsServiceSizes(int id, int serviceSizeId) =>
    "client/foods/$id/service-sizes/$serviceSizeId";

// Food Category
String getFoodCategory = "food/category-with-foods";

// Recipes
String getFoodRecipes = "food/category-with-recipes";
String getFoodRecipesDetail = "food/recipes/";
String addMealRecipe = "diet/meal-recipes";

// Edit Meal Foods
String editMealFood = "diet/meal-foods/";

//Schedules
String getSchedule = "diet/schedules";
String postSchedule = "diet/schedules";
String deleteSchedule = "diet/schedules/";
String addAdherence = "diet/log-adherences";

//Journal
String addJournal = "diet/log-journals";

//Photos
String logPhotos = "diet/log-photos";
String comparePhotos = "diet/progress/compare-photo";

// My foods
String storeFood = "client/foods";
String getMyFoods = "client/foods";
String setMyFoodsServiceSizes(int id) => "client/foods/$id/service-sizes";

//Data lists
String getNutrientTreeList = "food/nutrients/tree-list";
String getServingSizeUnits = "food/serving-size-units";

//Progress
String getWeightLogs = "diet/progress/weight";
String getMeasurementLogs = "diet/progress/body-measurement";
String getAdherenceLogs = "diet/progress/adherence";
String getComparePhotos = "diet/progress/compare-photo";
const String deleteWeight = "diet/weight-logs";
const String deleteMeasurementLogs = "diet/body-measurement-logs";

// add data
String addWeight = "diet/weight-logs";
String addMeasurementLogs = "diet/body-measurement-logs";

// Auto generate Dietplan
String autoGenerateDietPlan = "diet/assign-premade-dietplan";

// FAQ
String allFaqs = "faq/faqs/all";
String newsletterSubscribe = "newsletter/subscribe";

// Resources
String allResources = "resource/resources/all";

//Submit Coaching
String submitCoaching = "coaching/coachings";

//Content APIS
String tnc = "pages/terms-of-service";
String disclaimer = "pages/disclaimer";
String privacyPolicy = "pages/privacy-policy";

// Notification
String notification = "client/notification-settings";
